<div class="container-image image-bottom">
    <div id="display-center">
        <p>Awards</p>
        <p>- A Branch of CAMRA -</p>
    </div>
</div>

<section class="no-space-below">
    <img id="camra-logo" src="images/CAMRA-Logo.png" alt="CAMRA Logo">
    <h1 id="title">Vale of Glamorgan and Bridgend Awards <?php echo date('Y') ?></h1> <!-- php used here to keep the year up to date -->
    <div class="content">
        <p>Congratulations to this year's winners, nominated and voted for by the CAMRA members from a choice of nearly 200 recognised real ale pubs and clubs in the branch area.</p>
    </div>
</section>

<section class="container-gallery">

    <div class="card-container card-title">
        <h1>Vale of Glamorgan and Bridgend Pub of the Year "Highly Commended" category</h1>
    </div>

    <div class="card-set">
        <div class="card-container card-sm">
            <h1>Edmondes Arms, Cowbridge</h1>
            <img src="images/pubs/HighlyCommended_1.jpg" alt="image">
            <p class="textFit">A three-roomed pub with a strong local following. The building is of brick and local limestone with wooden floors, open fires and original features. A separate cosy lounge with a piano and a door to the small patio area which serves as a beer garden. Live bands play most Saturday evenings.</p>
        </div>

        <div class="card-container card-sm">
            <h1>Horseshoe Inn, Marcross</h1>
            <img src="images/pubs/HighlyCommended_2.jpg" alt="image">
            <p class="textFit">A beautiful 19th century pub offering a varied menu of good food and three excellent ales, usually one from a Welsh brewery. When sunny the beer garden is delightful and in winter the compact interior is cosy with a large log burner in the bar.</p>
        </div>

        <div class="card-container card-sm">
            <h1>Little Penybont Arms, Pencoed</h1>
            <img src="images/pubs/HighlyCommended_3.jpg" alt="image">
            <p class="textFit">A refurbished old cafe now a friendly micro-pub. Opened April 8 2015, it serves up to 6 changing beers on gravity and around 20 ciders - a real ale and real cider drinker's paradise!</p>
        </div>
    </div>

    <div class="card-set">
        <div class="card-container card-sm">
            <h1>Pilot, Penarth</h1>
            <img src="images/pubs/HighlyCommended_4.jpg" alt="image">
            <p class="textFit">Operated with emphasis on fine food, with interesting and high quality ales. Seating outside the front for warm weather, and a view across Cardiff Bay to the back. </p>
        </div>

        <div class="card-container card-sm">
            <h1>Star, Wick</h1>
            <img src="images/pubs/HighlyCommended_5.jpg" alt="image">
            <p class="textFit">The Star has gained a reputation for excellent food and great quality ale. Originally three farm cottages, the interior has a traditional bar plus a lounge/diner and has flagstones throughout.</p>
        </div>

        <div class="card-container card-sm">
            <h1>Old Swan Inn, Llantwit Major</h1>
            <img src="images/pubs/HighlyCommended_6.jpg" alt="image">
            <p class="textFit">The oldest pub in Llantwit Major with an ever changing range of ales, often featuring Welsh breweries. Excellent food is also a feature of this attractive and comfortable hostelry. Beer festivals in spring and summer.</p>
        </div>
    </div>

    <div class="card-container card-title">
        <h1>Vale of Glamorgan and Bridgend "Special Merit" category</h1>
    </div>

    <div class="card-set">
        <div class="card-container card-sm card-lg">
            <h1>Coach Inn, Bridgend</h1>
            <img src="images/pubs/SpecialMerit_1.jpg" alt="image">
            <p class="textFit">A staggering array of pumpclips pay testament to the enthusiasm of the proprietors (and customers) for good quality real ale and cider. Well supported beer festivals.
                The owners have also recently opened 1 Town Hall Square in Cowbridge.</p>
        </div>

        <div class="card-container card-sm card-lg">
            <h1>1 Town Hall Square, Cowbridge</h1>
            <img src="images/pubs/SpecialMerit_2.jpg" alt="image">
            <p class="textFit">Cowbridge's newest pub opened in Sept 2017 and specialises in cask and craft ales. There is a small bar with a seating area off it whilst upstairs are another two small rooms with more seats. Decor is traditional with exposed stonework, tiled and wooden floors, low beams and brewery memorabilia decorating the walls.</p>
        </div>
    </div>

    <div class="card-container card-title">
        <h1>Individual categories</h1>
    </div>

    <div class="card-container card-drop">
        <div class="card-column">
            <h1 class="card-pubtitle">Vale of Glamorgan & Bridgend Overall Winner Branch Pub of the Year 2018</h1>
            <span class="boxItem" onclick="openCol(0,'Cross Inn, Cwmfelin','Vale of Glamorgan & Bridgend Overall Winner Branch Pub of the Year 2018')"> &#8690; </span>
        </div>
        <div class="card-dropdown">
            <img src="images/pubs/OverallWinner.jpg" alt="image">
            <p class="textFit">This friendly multi-roomed pub with its own green-energy-run Cerddin Brewery is situated between Maesteg and Bridgend, with buses stopping at the front door and the railway station within walking distance. Excellent beer, a warm welcome, and good for the environment too!</p>
        </div>
    </div>

    <div class="card-container card-drop">
        <div class="card-column">
            <h1 class="card-pubtitle">Vale of Glamorgan Pub of the Year 2018</h1>
            <span class="boxItem" onclick="openCol(1, 'Golden Lion, Penarth', 'Vale of Glamorgan Pub of the Year 2018')"> &#8690;</span>
        </div>
        <div class="card-dropdown">
            <img src="images/pubs/PubOfTheYear.jpg" alt="image">
            <p>VoG and Bridgend CAMRA members voted for the Lion primarily for the superb quality of the three or four well-chosen ales from Welsh breweries, but also because it's a genuine pub, with layout and design that just makes it great to drink there.
                Other criteria include the friendly welcome, fast and efficient service, a role in the community with darts and football teams regularly attending, and value for money, not only the price on the handpumps but the great value food.</p>
        </div>
    </div>

    <div class="card-container card-drop">
        <div class="card-column">
            <h1 class="card-pubtitle">Vale of Glamorgan and Bridgend Cider Pub of the Year 2018</h1>
            <span class="boxItem" onclick="openCol(2, 'Plough & Harrow, Monknash', 'Vale of Glamorgan and Bridgend Cider Pub of the Year 2018')"> &#8690;</span>
        </div>
        <div class="card-dropdown">
            <img src="images/pubs/CiderPubOfTheYear.jpg" alt="image">
            <p>Renowned, welcoming 14th-century pub, originally a monastic farmhouse for Neath Abbey, with many original features remaining. Up to eight real ales available, four on handpump and the others direct from casks behind the bar, with local breweries well supported along with real cider and perry. Good home-cooked food served, and the large log fires add warmth in winter.</p>
        </div>
    </div>

    <div class="card-container card-drop">
        <div class="card-column">
            <h1 class="card-pubtitle">Vale of Glamorgan and Bridgend Club of the Year 2018</h1>
            <span class="boxItem" onclick="openCol(3, 'West End Club, Barry', 'Vale of Glamorgan and Bridgend Club of the Year 2018')"> &#8690;</span>
        </div>
        <div class="card-dropdown">
            <img src="images/pubs/ClubOfTheYear.jpg" alt="image">
            <p class="textFit">A welcoming atmosphere and an ever-changing range of real ales and ciders. Set on a hill overlooking Barry Old Harbour, the club welcomes visitors and hosts beer festivals in the spring and autumn, often featuring Welsh beers.</p>
        </div>
    </div>

    <div class="card-container card-drop">
        <div class="card-column">
            <h1 class="card-pubtitle">Vale of Glamorgan and Bridgend Most Improved Pub of the Year 2018</h1>
            <span class="boxItem" onclick="openCol(4, 'Tudor Tavern, Llantwit Major', 'Vale of Glamorgan and Bridgend Most Improved Pub of the Year 2018')"> &#8690;</span>
        </div>
        <div class="card-dropdown">
            <img src="images/pubs/MostImproved.jpg" alt="image">
            <p class="textFit">After decades of neglect, the new licensees have undertaken a total refit, transforming the pub into a worthy addition to Llantwit's collection of hostelries well worth a visit.</p>
        </div>
    </div>

    <div class="card-container card-drop">
        <div class="card-column">
            <h1 class="card-pubtitle">Vale of Glamorgan and Bridgend Community Pub of the Year 2018</h1>
            <span class="boxItem" onclick="openCol(5, 'Mountain Hare, Brynnau Gwynion', 'Vale of Glamorgan and Bridgend Community Pub of the Year 2018')"> &#8690;</span>
        </div>
        <div class="card-dropdown">
            <img src="images/pubs/CommunityPubOfTheYear.jpg" alt="image">
            <p class="textFit">A traditional Welsh village local, the pub has been in the same family for over forty years and boasts a traditional public bar and a lovely old stone walled lounge. One of the handpumps usually has one of the pub's own brews.</p>
        </div>
    </div>
</section>

<div class="container-image image-bottom"></div>

<!-- Select a navigation item, and make it active -->
<script>
    document.getElementById('awards').classList.add('active');
</script>