<div class="container-image">
    <div id="display-center">
        <p>Vale of Glamorgan & Bridgend</p>
        <p>- A branch of CAMRA -</p>
    </div>
</div>
<section>
    <img id="camra-logo" src="images/CAMRA-Logo.png" alt="CAMRA Logo">
    <h1 id="title">WELCOME</h1>
    <h2>Who are we?</h2>
    <div class="content">
        <p>The Campaign for Real Ale is an independent, voluntary organisation that fights for real ale, real pubs and consumer rights. We have over 188,000 members around the world and it's continuously growing</p>
        <p>This particular website is for the Vale of Glamorgan and Bridgend branch, if you want to see another branch
            <a href="http://www.camra.org.uk/camra-branches" target="_self">click here</a>. Our responsibilities include;</p>
        <ol>
            <li>Publicising our branch area's beer, cider and pub news on our <a href="https://www.facebook.com/Campaign-For-Real-Ale-CAMRA-Vale-of-Glamorgan-Bridgend-Branch-280055688703454">Facebook page</a>,</li>
            <li>Selecting the pubs from our area for inclusion in CAMRA's annual <a href="http://shop.camra.org.uk/books/good-beer-guide/good-beer-guide-2015.html">Good Beer Guide</a>,</li>
            <li>Choosing one as the branch area <a href="awards.php" target="_self">Pub Of The Year, Club Of The Year and Cider Pub Of The Year</a>,</li>
            <li>Organising regular <a href="meetings.php" target="_self">Branch Meetings</a> at various pubs throughout the Vale Of Glamorgan and Bridgend,</li>
            <li>Representing CAMRA and campaign on CAMRA issues in our area,</li>
            <li>Liaising with and report on the <a href="links.php" target="_self">Local Breweries</a> around our area to CAMRA headquarters,</li>
            <li>Maintaining the CAMRA database of Vale Of Glamorgan and Bridgend pubs <a href="https://whatpub.com/" target="_self">"WhatPub"</a> available online.</li>
        </ol>
    </div>
</section>

<section>
    <article class="half-content">
        <h1>The annual branch pub, club and cider pub winner.</h1>
        <p> As the days get shorter and the nights get colder, why not treat yourself to some more visits to pubs in the VoG and Bridgend; afterwards, let us know what you thought!</p>
    </article>
    <article class="half-content">
        <h1>Introducing <a onclick="document.querySelector('.targ').scrollIntoView({block: 'center', behavior: 'smooth'});">WhatPub</a>, the online pub guide chosen by you.</h1>
        <p> With over 160 eligible pubs in the VoG and Bridgend area, we could use your feedback to ensure that all the entries are fair and accurate.</p>
    </article>
</section>

<section>
    <article class="half-content">
        <a href="https://shop.camra.org.uk/goodbeerguide2018.html"><img src="images/banner.png" alt="Good Beer Guide"></a>
    </article>
    <article class="half-content">
        <h1>The Good Beer Guide</h1>
        <p> Every report we recieve regarding the quality of ale in the Vale will be taken into consideration when choosing entries for the next CAMRA good beer guide. </p>
    </article>
</section>

<section>
    <h1>About CAMRA</h1>
    <p>
        Formed in 1971, four like minded, real ale enthusiasts shared a disappointment with the increasingly poor quality of beer. CAMRA campaigns to have good quality real ales, ciders and perries to have thriving pubs and clubs in every community.
        CAMRA is an independent consumer campaign and our campaign objectives are set by our membership.
        Campaigns are run nationally, regionally and locally. Nationally, CAMRA produces the Great British Beer Festival, the Good Beer Guide, the Champion Beer of Britain Awards and the Pub of the Year Award.
        Thanks to the way Branches are structured, when you join the campaign you have the opportunity to join your nearest branch and get involved in the local campaigns, social activities and beer festivals.
        VoG and Bridgend CAMRA has a number of campaigns and events such as Pub of the Year Awards and regular social meet ups. If you want to get involved, please contact us or see our memberships page.
    </p>
</section>

<section>
    <article class="half-content whatpub-share targ">
        <h1>WhatPub</h1>
        <h2>The Campaign for Real Ale's online pub guide</h2>
        <p> As the UK's largest and most influential pub-going consumer organisation, CAMRA has its own online pub guide, with information sourced from real pub-goers.</p>
        <p> The guide at <a href="https://whatpub.com/login">WhatPub.com</a> can be used to search for pubs across the UK and then look up details such as opening times, descriptions, facilities and of course details of the real ale and cider on offer. </p>
        <p> WhatPub also complements the CAMRA Good Beer Guide; there's no way of searching specifically for Good Beer Guide pubs so you'll still need the book or Mobile App to find the very best real ale pubs.</p>
    </article>
    <article class="half-content whatpub-share" id="whatpub_logo">
        <a href="https://whatpub.com/login"><img src="images/WhatPubLogo.png" alt="WhatPub"></a>
    </article>
</section>

<div class="container-image image-bottom"></div>

<!-- Select a navigation item, and make it active -->
<script>
    document.getElementById('home').classList.add('active');
</script>