<div class="container-image image-bottom">
    <div id="display-center">
        <p>Join Us</p>
        <p>- A Branch of CAMRA -</p>
    </div>
</div>

<section>
    <img id="camra-logo" src="images/CAMRA-Logo.png" alt="CAMRA Logo">
    <h1 id="title">Join CAMRA</h1>
    <h2>The Campaign for Real Ale is a powerful champion for pub-goers and beer drinks</h2>
    <article class="half-content">
        <p>CAMRA campaigns tirelessly to support and promote pubs, real ale and consumer rights.</p>
        <p>
            Help support the British Brewing & Pub industry by enjoying the great benefits of a CAMRA membership; you can get access to a
            Quarterly magazine entitled "Beer", Monthly newspaper "What's Brewing" Free or reduced entry to over 160 beer festivals,
            £20 worth of JD Wetherpoon real ale vouchers (40x50p off a pint), Discounts on books including the Good Beer Guide For more details, and to join online, visit the
            <a href="http://www.camra.org.uk/"> main CAMRA website</a>.
        </p>
    </article>
    <article class="half-content" style="width:30%;">
        <a href="https://shop.camra.org.uk/goodbeerguide2018.html"><img src="images/campaignJoin.jpg" alt="Good Beer Guide"></a>
    </article>
</section>
<section>
    <h1 id="title">Beer Scoring</h1>
    <h2>What can you do as a CAMRA member</h2>
    <p>When you become a CAMRA member, you can tell us about the quality of beer in the pubs you visit.</p>
    <p>The National Beer Scoring System (NBSS) is a 0-5 point scale for judging beer quality in pubs. It is an easy to use system that has been designed to assist CAMRA branches in selecting pubs for the Good Beer Guide and also monitor beer quality by encouraging CAMRA members from any part of the world to report beer quality on any pub in the UK. </p>
    <h2>How you can take park</h2>
    <p>To submit your scores please visit <a href="https://whatpub.com/">'WhatPub'</a> where you can find your pub and rate accordingly.</p>
    <p>For those members without easy internet access, you can get NBSS cards to take with you to the pub and record the information.</p>

    <h2>What to record:</h2>
    <ol>
        <li>Your name & Membership Number,</li>
        <li>The date you visited the pub,</li>
        <li>The Name of the Pub,</li>
        <li>Where the pub is located,</li>
        <li>A score from 0 to 5,</li>
        <li>The name of the beer(s), although this is optional.</li>
    </ol>
    <p>Once you have submitted your scores, your Branch GBG Co-ordinators can view the scores and add them to the data already gathered to determine which pubs should be awarded entries into the next CAMRA Good Beer Guide.</p>
</section>

<div class="container-image image-bottom"></div>

