<div class="container-image image-bottom">
    <div id="display-center">
        <p>Links</p>
        <p>- A Branch of CAMRA -</p>
    </div>
</div>

<section>
    <img id="camra-logo" src="images/CAMRA-Logo.png" alt="CAMRA Logo">
    <article class="half-content">
        <h1 id="title">Links</h1>
        <h2>The CAMRA main website</h2>
        <p><a href="http://www.camra.org.uk/">www.camra.org.uk</a></p>

        <h2>The six breweries in the Vale of Glamorgan and Bridgend area:</h2>
        <p><a href="http://www.vogbrewery.co.uk/">Vale of Glamorgan Brewery</a></p>
        <p><a href="http://www.cerddinbrewery.co.uk/">Cerddin Brewery</a></p>
        <p><a href="http://www.mountainhare.co.uk/">Mountain Hare Brewery</a></p>
        <p><a href="http://www.tomosalilford.com/">Tomos and Lilford</a></p>
        <p><a href="https://www.facebook.com/bangonbrewery">Bang On Brewery</a></p>
        <p><a href="https://bontbrew.com">BontBrew</a></p>

        <h2>Some of our neighbouring branch's websites:</h2>
        <p><a href="http://www.gwentcamra.org.uk/">Gwent Branch</a></p>
        <p><a href="http://www.cardiffcamra.co.uk//">Cardiff Branch</a></p>
        <p><a href="http://www.midglamcamra.org.uk/">Mid-Glamorgan Branch</a></p>
    </article>
</section>

<section>
    <h1 id="title">Contact us</h1>
    <h2>If you ever want to get in contact with a member of the team, here are their details.</h2>
    <table>
        <tr>
            <th>Position</th>
            <th>Name</th>
            <th style="width: 20px">Contact Information</th>
        </tr>
        <tr>
            <td>Chairman</td>
            <td>Gerwyn Thomas</td>
            <td><a href="mailto:chairman@vogcamra.org.uk">chairman@vogcamra.org.uk</a></td>
        </tr>
        <tr>
            <td>Branch Contact and Pubs Officer, VoG</td>
            <td>John Chapman</td>
            <td><p>01446 794568</p><a href="mailto:pubsofficervale@vogcamra.org.uk">pubsofficervale@vogcamra.org.uk</a></td>
        </tr>
        <tr>
            <td>Secretary</td>
            <td>Gerwyn Thomas</td>
            <td><p><a href="mailto:secretary@vogcamra.org.uk">secretary@vogcamra.org.uk</a></p></td>
        </tr>
        <tr>
            <td>Pubs Officer, Bridgend</td>
            <td>Mick Cheal</td>
            <td><a href="mailto:pubsofficerbridgend@vogcamra.org.uk">pubsofficerbridgend@vogcamra.org.uk</a></td>
        </tr>
        <tr>
            <td>Press and Publicity Officer</td>
            <td>Neil Goodman</td>
            <td><p><a href="mailto:press@vogcamra.org.uk">press@vogcamra.org.uk</a></p><p><a href="mailto:publicity@vogcamra.org.uk">publicity@vogcamra.org.uk</a></p></td>
        </tr>
        <tr>
            <td>Website Coordinator</td>
            <td>Nigel Lewis</td>
            <td><a href="mailto:website@vogcamra.org.uk">website@vogcamra.org.uk</a></td>
        </tr>
        <tr>
            <td>Membership Secretary</td>
            <td>Neil Goodman</td>
            <td><a href="mailto:membership@vogcamra.org.uk">membership@vogcamra.org.uk</a></td>
        </tr>
        <tr>
            <td>Treasurer</td>
            <td>Andy Hurst</td>
            <td><a href="mailto:treasurer@vogcamra.org.uk">treasurer@vogcamra.org.uk</a></td>
        </tr>
        <tr>
            <td>Whatpub</td>
            <td>Neil Warnock</td>
            <td><a href="mailto:whatpub@vogcamra.org.uk">whatpub@vogcamra.org.uk</a></td>
        </tr>
    </table>
</section>

<div class="container-image image-bottom"></div>
