<div class="container-image image-bottom">
    <div id="display-center">
        <p>Meetings</p>
        <p>- A Branch of CAMRA -</p>
    </div>
</div>

<section>
    <img id="camra-logo" src="images/CAMRA-Logo.png" alt="CAMRA Logo">
    <h1 id="title">Upcoming Branch Meetings</h1>
    <p>Here you can keep up to date with our most recent meetings.</p>
    <table id="currentYear">
        <tr> <th class="table-title">2019</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Thursday 3 January</td>
            <td>8pm</td>
            <td>Walston Castle, Wenvoe</td>
        </tr>
        <tr>
            <td>Thursday 21 February</td>
            <td>8pm</td>
            <td>Prince of Wales, Kenfig</td>
        </tr>
        <tr>
            <td>Thursday 11 April</td>
            <td>8pm</td>
            <td>The Boathouse, Sully</td>
        </tr>
    </table>
</section>

<section>
    <h1 id="title">Previous Meetings</h1>
    <p>If you want to keep track of our previous meetings, see below.</p>
    <table id="currentYear">
        <tr> <th class="table-title">2018</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Thursday 7 December</td>
            <td>8pm</td>
            <td>Walston Castle, Wenvoe</td>
        </tr>
        <tr>
            <td>Thursday 4 January</td>
            <td>8pm</td>
            <td>1 Town Hall Square, Cowbridge</td>
        </tr>
        <tr>
            <td>Thursday 15 February</td>
            <td>8pm</td>
            <td>Star Inn, Wick</td>
        </tr>
        <tr>
            <td>Thursday 15 March</td>
            <td>8pm</td>
            <td>Cefn Mably, Penarth</td>
        </tr>
        <tr>
            <td>Thursday 11 April</td>
            <td>8pm</td>
            <td>Edmondes Arms, Cowbridge</td>
        </tr>
        <tr>
            <td>Thursday 17 May</td>
            <td>8pm</td>
            <td>Cross Inn, Cwmfelin</td>
        </tr>
        <tr>
            <td>Thursday 21 June</td>
            <td>8pm</td>
            <td> Llantwit Major Rugby Club </td>
        </tr>
        <tr>
            <td>Thursday 19 July</td>
            <td>8pm</td>
            <td>Windsor Hotel, Penarth </td>
        </tr>
    </table>

    <table>
        <tr> <th class="table-title">2017</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Thursday 12 January</td>
            <td>8pm</td>
            <td>Star Inn, Wick</td>
        </tr>
        <tr>
            <td>Thursday 23 February</td>
            <td>8pm</td>
            <td>West End Club, Barry</td>
        </tr>
        <tr>
            <td>Thurs 30th March</td>
            <td>8pm</td>
            <td>Lorelei, Porthcawl</td>
        </tr>
        <tr>
            <td>Thurs 18th May</td>
            <td>8pm</td>
            <td>Cross Keys, Dinas Powys</td>
        </tr>
        <tr>
            <td>Thurs 22th June</td>
            <td>8pm</td>
            <td>Fox & Hounds, St Brides Major</td>
        </tr>
        <tr>
            <td>Thurs 24th August</td>
            <td>8pm</td>
            <td>AGM - Barry West End Club, Barry</td>
        </tr>
        <tr>
            <td>Thurs 5th October</td>
            <td>8pm</td>
            <td>Blacksmith's Arms, Llanmaes</td>
        </tr>
        <tr>
            <td>Thurs 2nd November</td>
            <td>8pm</td>
            <td>Sawyer's Arms, Maesteg</td>
        </tr>
    </table>
    <table>
        <tr> <th class="table-title">2016</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Thurs 7th January</td>
            <td>8pm</td>
            <td>Sawyers Arms in Maesteg</td>
        </tr>
        <tr>
            <td>Thurs 18th February</td>
            <td>8pm</td>
            <td>Boverton Castle, Boverton</td>
        </tr>
        <tr>
            <td>Thurs 21st April</td>
            <td>8pm</td>
            <td>Mountain Hare, Brynnau Gwynion</td>
        </tr>
        <tr>
            <td>Thurs 9th June</td>
            <td>8pm</td>
            <td>Sir Samuel Romilly, Barry</td>
        </tr>
        <tr>
            <td>Thurs 11th August</td>
            <td>8pm</td>
            <td>Prince of Wales, Kenfig</td>
        </tr>
        <tr>
            <td>Thurs 15th September</td>
            <td>8pm</td>
            <td>Llantwit Major Rugby Club (AGM)</td>
        </tr>
        <tr>
            <td>Thurs 27th October</td>
            <td>8pm</td>
            <td>Ex-Servicemen's Club, Penarth</td>
        </tr>
        <tr>
            <td>Thurs 24th November</td>
            <td>8pm</td>
            <td>Horsehoe Inn, Marcross</td>
        </tr>
    </table>
    <table>
        <tr> <th class="table-title">2015</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Thursday 8th January</td>
            <td>8pm</td>
            <td>Red Lion, Bonvilston</td>
        </tr>
        <tr>
            <td>Thursday 19th February</td>
            <td>7:30pm</td>
            <td>Llantwit Major RFC</td>
        </tr>
        <tr>
            <td>Thurs 26th March</td>
            <td>8pm</td>
            <td>Farmers Arms, Nottage</td>
        </tr>
        <tr>
            <td>Wed 6th May</td>
            <td>8pm</td>
            <td>The Blaengarw Hotel, Blaengarw</td>
        </tr>
        <tr>
            <td>Thurs 18th June</td>
            <td>7:30pm</td>
            <td>The Plough & Harrow, Monknash</td>
        </tr>
        <tr>
            <td>Thurs 30th July</td>
            <td>8pm</td>
            <td>Cross Inn, Dinas Powis</td>
        </tr>
        <tr>
            <td>Saturday 19th September</td>
            <td>2pm</td>
            <td>Cabo Roche, Bridgend</td>
        </tr>
        <tr>
            <td>Thursday 29th October</td>
            <td>8pm</td>
            <td>Edmondes Arms, Cowbridge</td>
        </tr>
        <tr>
            <td>Saturday 21st November</td>
            <td>t.b.a</td>
            <td>Bears Head, Penarth</td>
        </tr>
        <tr>
            <td>Thursday 10th December</td>
            <td>8pm</td>
            <td>Fox & Hounds, St Brides</td>
        </tr>
    </table>
    <table>
        <tr> <th class="table-title">2014</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Wednesday 8th January</td>
            <td>8pm</td>
            <td>Golden Lion, Penarth</td>
        </tr>
        <tr>
            <td>Thursday 20th February</td>
            <td>8pm</td>
            <td>Wyndham Arms, Bridgend</td>
        </tr>
        <tr>
            <td>Wednesday 26th March 2014</td>
            <td>7:30pm</td>
            <td>Red Fox, Penllyn</td>
        </tr>
        <tr>
            <td>Wednesday 23rd April</td>
            <td>8pm</td>
            <td>Barry West End Club</td>
        </tr>
        <tr>
            <td>Thursday 22nd May</td>
            <td>8pm</td>
            <td>Angel Inn, Mawdlam</td>
        </tr>
        <tr>
            <td>Thurs 10th July</td>
            <td>7:30pm</td>
            <td>Blacksmiths Arms, Llanmaes</td>
        </tr>
        <tr>
            <td>Saturday 30th August</td>
            <td>t.b.a</td>
            <td>Edmondes Arms, Cowbridge</td>
        </tr>
        <tr>
            <td>Thursday 9th October</td>
            <td>8pm</td>
            <td>Bear's Head, Penarth</td>
        </tr>
        <tr>
            <td>Thursday 9th October</td>
            <td>8pm</td>
            <td>Bear's Head, Penarth</td>
        </tr>
    </table>
    <table>
        <tr> <th class="table-title">2013</th> </tr>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
        </tr>
        <tr>
            <td>Thursday 3rd January</td>
            <td>7pm</td>
            <td>Wyndham Arms, Bridgend</td>
        </tr>
        <tr>
            <td>Thursday 7th February</td>
            <td>7:30pm</td>
            <td>Old White Hart, Llantwit Major</td>
        </tr>
        <tr>
            <td>Wednesday 13th March</td>
            <td>8pm</td>
            <td>Windsor, Penarth</td>
        </tr>
        <tr>
            <td>Thursday 18th April</td>
            <td>8pm</td>
            <td>Red Fox, Penllyn</td>
        </tr>
        <tr>
            <td>Thursday 23rd May</td>
            <td>7:30pm</td>
            <td>Pheasant, Pen-Y-Fai</td>
        </tr>
        <tr>
            <td>Wednesday 19th June</td>
            <td>8pm</td>
            <td>Plough & Harrow, Monknash</td>
        </tr>
        <tr>
            <td>Wednesday 24th July</td>
            <td>8pm</td>
            <td>Mountain Hare, Brynna Gwynion</td>
        </tr>
        <tr>
            <td>Saturday 31st August</td>
            <td>2pm</td>
            <td>Barry West End Club, Barry</td>
        </tr>
        <tr>
            <td>Wednesday 16th October</td>
            <td>8pm</td>
            <td>Star Inn, Wick</td>
        </tr>
        <tr>
            <td>Thursday 21st November</td>
            <td>8pm</td>
            <td>Hare & Hounds, Aberthin</td>
        </tr>
    </table>
</section>
<div class="container-image image-bottom"></div>