<footer>
    <base href="index.html" target="_blank"/>
    <h3>&copy Campaign for Real Ale 2014. All rights reserved.</h3>
    <div class="footer-wrapper">
        <span class="footer-social"> <a href="https://www.facebook.com/Campaign-For-Real-Ale-CAMRA-Vale-of-Glamorgan-Bridgend-Branch-280055688703454"> <img src="images/Facebook.png" alt="Facebook"> </a> </span> <!-- Facebook -->
        <span class="footer-social"> <a href="https://twitter.com/CAMRA_Official?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"> <img src="images/Twitter.png" alt="Twitter"> </a> </span>   <!-- Twitter -->
    </div>
</footer>
<!-- Script -->
<script src="js/myScripts.js"></script>